name: cdx_reactiveforms_example
description: Example app demonstrating all form types in cdx_reactiveforms
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.3.0
  json_annotation: ^4.9.0
  file_picker: ^8.1.4
  cdx_reactiveforms:
    path: ../
  cdx_core:
    path: ../../cdx_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

